# =============================================================================
# dev-ap2 / eks-tf
# =============================================================================
dev-ap2-eks-tf:validate:
  extends: .terraform_base
  stage: validate
  variables:
    TF_ROOT: account/aws-dev-ap2/eks-tf
  script:
    - terraform validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - account/aws-dev-ap2/eks-tf/**/*
    - if: $CI_PIPELINE_SOURCE != "push"
      when: manual

dev-ap2-eks-tf:plan:
  extends: .terraform_base
  stage: plan
  variables:
    TF_ROOT: account/aws-dev-ap2/eks-tf
  script:
    - terraform plan -var-file=environments/dev.tfvars -out=tfplan
  artifacts:
    paths:
      - ${TF_ROOT}/tfplan
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - account/aws-dev-ap2/eks-tf/**/*
    - if: $CI_PIPELINE_SOURCE != "push"
      when: manual

dev-ap2-eks-tf:apply:
  extends: .terraform_base
  stage: apply
  resource_group: dev-ap2-eks-tf
  variables:
    TF_ROOT: account/aws-dev-ap2/eks-tf
  script:
    - terraform apply -auto-approve tfplan
  dependencies:
    - dev-ap2-eks-tf:plan
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - account/aws-dev-ap2/eks-tf/**/*
      when: manual
    - if: $CI_PIPELINE_SOURCE != "push"
      when: manual

# =============================================================================
# dev-ap2 / tgw
# =============================================================================
dev-ap2-tgw:plan:
  extends: .terraform_base
  stage: plan
  variables:
    TF_ROOT: account/aws-dev-ap2/tgw
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - ${TF_ROOT}/tfplan
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - account/aws-dev-ap2/tgw/**/*
    - if: $CI_PIPELINE_SOURCE != "push"
      when: manual

dev-ap2-tgw:apply:
  extends: .terraform_base
  stage: apply
  resource_group: dev-ap2-tgw
  variables:
    TF_ROOT: account/aws-dev-ap2/tgw
  script:
    - terraform apply -auto-approve tfplan
  dependencies:
    - dev-ap2-tgw:plan
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - account/aws-dev-ap2/tgw/**/*
      when: manual
    - if: $CI_PIPELINE_SOURCE != "push"
      when: manual
