# =============================================================================
# dev-ue1 / eks-main
# =============================================================================
dev-ue1-eks-main:plan:
  extends: .terraform_base
  stage: plan
  variables:
    TF_ROOT: account/aws-dev-ue1/eks-main
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - ${TF_ROOT}/tfplan
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - account/aws-dev-ue1/eks-main/**/*
    - if: $CI_PIPELINE_SOURCE != "push"
      when: manual

dev-ue1-eks-main:apply:
  extends: .terraform_base
  stage: apply
  resource_group: dev-ue1-eks-main
  variables:
    TF_ROOT: account/aws-dev-ue1/eks-main
  script:
    - terraform apply -auto-approve tfplan
  dependencies:
    - dev-ue1-eks-main:plan
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - account/aws-dev-ue1/eks-main/**/*
      when: manual
    - if: $CI_PIPELINE_SOURCE != "push"
      when: manual
