# =============================================================================
# manage-ap3 / tgw
# =============================================================================
manage-ap3-tgw:validate:
  extends: .terraform_base
  stage: validate
  variables:
    TF_ROOT: account/aws-manage-ap3/tgw
  script:
    - terraform validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - account/aws-manage-ap3/tgw/**/*
    - when: manual
      allow_failure: true

manage-ap3-tgw:plan:
  extends: .terraform_base
  stage: plan
  variables:
    TF_ROOT: account/aws-manage-ap3/tgw
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - ${TF_ROOT}/tfplan
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - account/aws-manage-ap3/tgw/**/*
    - when: manual
      allow_failure: true

manage-ap3-tgw:apply:
  extends: .terraform_base
  stage: apply
  resource_group: manage-ap3-tgw
  variables:
    TF_ROOT: account/aws-manage-ap3/tgw
  script:
    - terraform apply -auto-approve tfplan
  dependencies:
    - manage-ap3-tgw:plan
  rules:
    - when: manual
      allow_failure: true

# =============================================================================
# manage-ap3 / vpc
# =============================================================================
manage-ap3-vpc:validate:
  extends: .terraform_base
  stage: validate
  variables:
    TF_ROOT: account/aws-manage-ap3/vpc
  script:
    - terraform validate
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - account/aws-manage-ap3/vpc/**/*
    - when: manual
      allow_failure: true

manage-ap3-vpc:plan:
  extends: .terraform_base
  stage: plan
  variables:
    TF_ROOT: account/aws-manage-ap3/vpc
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - ${TF_ROOT}/tfplan
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - account/aws-manage-ap3/vpc/**/*
    - when: manual
      allow_failure: true

manage-ap3-vpc:apply:
  extends: .terraform_base
  stage: apply
  resource_group: manage-ap3-vpc
  variables:
    TF_ROOT: account/aws-manage-ap3/vpc
  script:
    - terraform apply -auto-approve tfplan
  dependencies:
    - manage-ap3-vpc:plan
  rules:
    - when: manual
      allow_failure: true
